version: '3'
services:
  mysql-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=9004
      - MYSQL_DATABASE=apibusqueda
      - MYSQL_USER=test
      - MYSQL_PASSWORD=9004
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  apirest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql-container
volumes:
  mysql-data:
